services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - video-chat-service
      - room-service
    restart: always
    env_file:
      - .env.local
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env.local
    networks:
      - app-network

  room-service:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    restart: always
    env_file:
      - .env.local
    networks:
      - app-network

  video-chat-service:
    build:
      context: ./video-chat-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    restart: always
    env_file:
      - .env.local
    networks:
      - app-network

networks:
  app-network:
