services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api-gateway:
    image: tushar03dev/connectify-backend:api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - auth-service
      - room-service
      - video-chat-service-1
      - video-chat-service-2
      - video-chat-service-3
    env_file:
      - .env.api-gateway
    networks:
      - app-network

  auth-service:
    image: tushar03dev/connectify-backend:auth-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    env_file:
      - .env.auth-service
    networks:
      - app-network

  room-service:
    image: tushar03dev/connectify-backend:room-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    env_file:
      - .env.room-service
    networks:
      - app-network

  video-chat-service-1:
    image: tushar03dev/connectify-backend:video-chat-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    env_file:
      - .env.video-chat-service
    networks:
      - app-network

  video-chat-service-2:
    image: tushar03dev/connectify-backend:video-chat-service
    ports:
      - "5004:5003"
    depends_on:
      - mongo
    env_file:
      - .env.video-chat-service
    networks:
      - app-network

  video-chat-service-3:
    image: tushar03dev/connectify-backend:video-chat-service
    ports:
      - "5005:5003"
    depends_on:
      - mongo
    env_file:
      - .env.video-chat-service
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
