services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api-gateway:
    image: tushar03dev/connectify-backend:api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - video-chat-service
      - room-service
    restart: always
    env_file:
      - .env.production
    networks:
      - app-network

  auth-service:
    image: tushar03dev/connectify-backend:auth-service
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env.production
    networks:
      - app-network

  room-service:
    image: tushar03dev/connectify-backend:room-service
    ports:
      - "5002:5002"
    restart: always
    env_file:
      - .env.production
    networks:
      - app-network

  video-chat-service:
    image: tushar03dev/connectify-backend:video-chat-service
    ports:
      - "5003:5003"
    restart: always
    env_file:
      - .env.production
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
