name: Build & Deploy Microservices to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Detect Changed Services
        id: changes
        run: |
          CHANGED_SERVICES=""
          for service in api-gateway auth-service room-service video-chat-service; do
            if git diff --quiet HEAD^ HEAD -- backend/$service; then
              echo "$service unchanged"
            else
              echo "$service changed"
              CHANGED_SERVICES="$CHANGED_SERVICES $service"
            fi
          done
          echo "services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT

      - name: Build & Push Changed Docker Images
        if: steps.changes.outputs.services != ''
        run: |
          for service in ${{ steps.changes.outputs.services }}; do
            IMAGE_NAME="tushar03dev/connectify-backend:$service"
            echo "Building and pushing $IMAGE_NAME"
            docker build --cache-from=$IMAGE_NAME -t $IMAGE_NAME ./backend/$service
            docker push $IMAGE_NAME
          done

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -o ServerAliveCountMax=3 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            docker compose pull
            docker compose down
          
            # Start core services first
            docker compose up -d mongo redis rabbitmq
          
            # Wait until services are healthy
            echo "Waiting for Mongo to be healthy..."
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q mongo))" = "healthy" ]; do
              sleep 2
            done
          
            echo "Waiting for Redis to be healthy..."
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q redis))" = "healthy" ]; do
              sleep 2
            done
          
            echo "Waiting for RabbitMQ to be healthy..."
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q rabbitmq))" = "healthy" ]; do
              sleep 2
            done
          
            echo "Core services are healthy. Starting application services..."
            docker compose up -d auth-service room-service video-chat-service-1 video-chat-service-2 video-chat-service-3 api-gateway
          
            docker image prune -af
          EOF
