name: Build & Deploy Microservices to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Detect Changed Services
        id: changes
        run: |
          CHANGED_SERVICES=""
          for service in api-gateway auth-service room-service video-chat-service; do
            if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
              git fetch --unshallow
            fi

            if git diff --quiet HEAD~1 HEAD -- backend/$service 2>/dev/null; then
              echo "$service unchanged"
            else
              echo "$service changed"
              CHANGED_SERVICES="$CHANGED_SERVICES $service"
              IMAGE_NAME="tushar03dev/connectify-backend:$service"
              docker build -t $IMAGE_NAME ./backend/$service
              docker push $IMAGE_NAME
            fi
          done
          echo "services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -af
          EOF
